### ISSUE TITLE
Internal discussion: the variance array

### ISSUE THREAD

**Issue by lucarizzi** [Mosfire-DataReductionPipeline/MosfireDRP#6]
I am creating a new issue with the same topic as the one submitted by Scott, so that we can have an internal discussion about why the S/N calculated using the rms of a spectrum is different than the variance array produced by the pipeline.

Seems like a questions that the pipeline experts might be able to address, but I am happy to try to dig deep into the code and try to find out how the variance is calculated and if we are all happy with it.

Anybody else wants to contribute?

Reported by Joo Yoon (UCSB): The S/N calculated using the rms of an extracted spectrum is significantly different than the variance array produced by the MOSFIRE DRP. In this case, the S/N level of an emission line detection was 1.5 using the variance array and 12 when calculated directly from the spectrum. It should be noted that the observers anticipated a S/N detection level of 3-5 and believe the error array to be too high and the rms of the spectrum to be too low.

**Comment by MosfireDRP** [comment]
Thank you all for the discussion. I am very much convinced that the pipeline is doing the right thing and that we need more information from the user in order to understand where his question is coming from, as you suggest.

Is anybody interested in following up with him by responding to the issue he submitted ? 
if not, I am happy to summarize this discussion and reply to the submitted issue.

Luca
